apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-postgres.rules-{{ .Values.prometheus.appName }}
  namespace: {{ .Release.Namespace }}
spec:
  groups:
  - name: {{ .Values.prometheus.appName }}-postgresRoleAlerts
    rules:
      - alert: {{ .Values.prometheus.appName }}-PostgresPodNotLeader
        expr: kube_pod_labels{pod="corvina-postgresql-0", namespace="{{ .Release.namespace }}", label_spilo_role="master"} == 0
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "corvina-postgresql-0 is not the leader"
          description: "The corvina-postgresql-0 pod in namespace 'prod' is no longer the leader in the PostgreSQL cluster."
