apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Values.prometheus.appName }}-prometheus-istio.rules
  namespace: {{ .Release.Namespace }}
spec:
  groups:
  - name: {{ .Values.prometheus.appName }}-istioAlerts
    rules:
      - alert: {{ .Values.prometheus.appName }}-HighErrorRate
        expr: increase(istio_requests_total{namespace="{{ .Release.Namespace }}", response_code=~"5.."}[5m]) / increase(istio_requests_total{namespace="{{ .Release.Namespace }}"}[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High rate of 5xx errors in Istio traffic"
          description: "Requests returning 5xx in the last 5m"
