revision: corvina-app-[| .Name |]
global:
  istioNamespace: corvina-app-[| .Name |]
  configValidation: true
  defaultPodDisruptionBudget:
    enabled: false
pilot:
  autoscaleEnabled: false
  env:
    ENABLE_ENHANCED_RESOURCE_SCOPING: true
    PILOT_SCOPE_GATEWAY_TO_NAMESPACE: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
meshConfig:
  discoverySelectors:
  - matchLabels:
      kubernetes.io/metadata.name: corvina-app-[| .Name |]
