istio-gateway:
  service:
    type: ClusterIP

tag: latest-master
imagePullPolicy: IfNotPresent

postgresql:
  global:
    storageClass: local-path

[| if .RedisEnabled |]
redis:
  global:
    storageClass: local-path
    defaultStorageClass: local-path
[|- end |]

[| if .RabbitEnabled |]
rabbitmq:
  storageClass: local-path
[|- end |]

service:
  extraCa:
    secret: corvina-app-[| .Name |]-prod-tls

[| if .StasherEnabled |]
stasher:
  extraCa:
    secret: corvina-app-[| .Name |]-prod-tls
[|- end |]

registration:
  enabled: true

backup:
  enabled: false