istio-gateway:
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 10m

imagePullPolicy: IfNotPresent   # necessary for scripts/replace-images.minikube.sh

postgresql:
  global:
    storageClass: csi-hostpath-sc
  primary:
    resources:
      requests:
        cpu: 10m

[| if .RedisEnabled -|]
redis:
  global:
    storageClass: csi-hostpath-sc
    defaultStorageClass: csi-hostpath-sc
  master:
    resources:
      requests:
        cpu: 10m
[|- end |]

[| if .RabbitEnabled -|]
rabbitmq:
  storageClass: csi-hostpath-sc
  resources:
    requests:
      cpu: 10m
[|- end |]

app:
  resources:
    requests:
      cpu: 10m

service:
  extraCa:
    secret: corvina-app-[| .Name |]-prod-tls
  resources:
    requests:
      cpu: 10m

[| if .StasherEnabled -|]
stasher:
  extraCa:
    secret: corvina-app-[| .Name |]-prod-tls
  resources:
    requests:
        cpu: 10m
[|- end |]

registration:
  enabled: true
  namespace: prod

backup:
  enabled: false
