on:
  push:

name: Mirror repository

jobs:
  mirror:
    name: Mirror repository
    runs-on: ubuntu-24.04
    steps:
      - uses: Corvina-R-D/corvina-github-public-actions/mirror-public-repository@v1
        with:
          target: https://x-token-auth:${{ secrets.BITBUCKET_ACCESS_TOKEN }}@bitbucket.org/exorint/mirror-create-corvina-app.git